on: workflow_dispatch
jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notifications
    steps:
    - name: IRC notification
      uses: Gottox/irc-message-action@v1.3.1
      with:
        channel: '#projectfnf'
        nickname: ProjectFNF_Bot
        message: |-
          ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
